---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: go-lev
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: go-lev
  targetCPUUtilizationPercentage: 80
