---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: go-lev
    maintainer: team-ops
  name: go-lev
spec:
  clusterIP: None
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: go-lev
  sessionAffinity: None
  type: ClusterIP
